
//! Autogenerated weights for `pallet_agent_attestation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-2004`, CPU: `Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_agent_attestation
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/agent-attestation/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_agent_attestation`.
pub trait WeightInfo {
	fn register_node() -> Weight;
	fn heartbeat() -> Weight;
	fn submit_attestation() -> Weight;
	fn challenge_attestation() -> Weight;
	fn confirm_attestation() -> Weight;
	fn resolve_challenge() -> Weight;
	fn update_capability() -> Weight;
	fn submit_benchmark_claim() -> Weight;
	fn challenge_benchmark() -> Weight;
	fn resolve_benchmark() -> Weight;
	fn update_benchmark_score() -> Weight;
}

/// Weights for `pallet_agent_attestation` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AgentAttestation::Nodes` (r:1 w:1)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3688`
		// Minimum execution time: 31_590_000 picoseconds.
		Weight::from_parts(32_080_000, 3688)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:1)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `172`
		//  Estimated: `3688`
		// Minimum execution time: 32_870_000 picoseconds.
		Weight::from_parts(33_611_000, 3688)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:0)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::AttesterTaskCount` (r:1 w:1)
	/// Proof: `AgentAttestation::AttesterTaskCount` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::NextAttestationId` (r:1 w:1)
	/// Proof: `AgentAttestation::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::Attestations` (r:0 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn submit_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `3688`
		// Minimum execution time: 72_950_000 picoseconds.
		Weight::from_parts(81_340_000, 3688)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AgentAttestation::Attestations` (r:1 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn challenge_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3901`
		// Minimum execution time: 31_970_000 picoseconds.
		Weight::from_parts(42_030_000, 3901)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Attestations` (r:1 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::NextIntentId` (r:1 w:1)
	/// Proof: `X402Settlement::NextIntentId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::SettlementReceipts` (r:0 w:1)
	/// Proof: `X402Settlement::SettlementReceipts` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn confirm_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3901`
		// Minimum execution time: 75_780_000 picoseconds.
		Weight::from_parts(87_500_000, 3901)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AgentAttestation::Attestations` (r:1 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `352`
		//  Estimated: `3901`
		// Minimum execution time: 89_830_000 picoseconds.
		Weight::from_parts(96_950_000, 3901)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:0)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::AgentCapabilities` (r:1 w:1)
	/// Proof: `AgentAttestation::AgentCapabilities` (`max_values`: None, `max_size`: Some(2702), added: 5177, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::ModelProviders` (r:0 w:2)
	/// Proof: `AgentAttestation::ModelProviders` (`max_values`: None, `max_size`: Some(323), added: 2798, mode: `MaxEncodedLen`)
	fn update_capability() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `6167`
		// Minimum execution time: 44_550_000 picoseconds.
		Weight::from_parts(51_441_000, 6167)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:0)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::MinerClaimCount` (r:1 w:1)
	/// Proof: `AgentAttestation::MinerClaimCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::MinerBenchmark` (r:1 w:1)
	/// Proof: `AgentAttestation::MinerBenchmark` (`max_values`: None, `max_size`: Some(330), added: 2805, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::NextBenchmarkClaimId` (r:1 w:1)
	/// Proof: `AgentAttestation::NextBenchmarkClaimId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:0 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	fn submit_benchmark_claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `3795`
		// Minimum execution time: 81_320_000 picoseconds.
		Weight::from_parts(90_120_000, 3795)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:1 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn challenge_benchmark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `416`
		//  Estimated: `3859`
		// Minimum execution time: 64_430_000 picoseconds.
		Weight::from_parts(73_880_000, 3859)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:1 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn resolve_benchmark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `3859`
		// Minimum execution time: 89_870_000 picoseconds.
		Weight::from_parts(96_281_000, 3859)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `AgentAttestation::MinerBenchmark` (r:1 w:0)
	/// Proof: `AgentAttestation::MinerBenchmark` (`max_values`: None, `max_size`: Some(330), added: 2805, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:1 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	fn update_benchmark_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3859`
		// Minimum execution time: 42_540_000 picoseconds.
		Weight::from_parts(47_420_000, 3859)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `AgentAttestation::Nodes` (r:1 w:1)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3688`
		// Minimum execution time: 31_590_000 picoseconds.
		Weight::from_parts(32_080_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:1)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	fn heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `172`
		//  Estimated: `3688`
		// Minimum execution time: 32_870_000 picoseconds.
		Weight::from_parts(33_611_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:0)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::AttesterTaskCount` (r:1 w:1)
	/// Proof: `AgentAttestation::AttesterTaskCount` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::NextAttestationId` (r:1 w:1)
	/// Proof: `AgentAttestation::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::Attestations` (r:0 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn submit_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `3688`
		// Minimum execution time: 72_950_000 picoseconds.
		Weight::from_parts(81_340_000, 3688)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AgentAttestation::Attestations` (r:1 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn challenge_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3901`
		// Minimum execution time: 31_970_000 picoseconds.
		Weight::from_parts(42_030_000, 3901)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Attestations` (r:1 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::NextIntentId` (r:1 w:1)
	/// Proof: `X402Settlement::NextIntentId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::SettlementReceipts` (r:0 w:1)
	/// Proof: `X402Settlement::SettlementReceipts` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn confirm_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3901`
		// Minimum execution time: 75_780_000 picoseconds.
		Weight::from_parts(87_500_000, 3901)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AgentAttestation::Attestations` (r:1 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `352`
		//  Estimated: `3901`
		// Minimum execution time: 89_830_000 picoseconds.
		Weight::from_parts(96_950_000, 3901)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:0)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::AgentCapabilities` (r:1 w:1)
	/// Proof: `AgentAttestation::AgentCapabilities` (`max_values`: None, `max_size`: Some(2702), added: 5177, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::ModelProviders` (r:0 w:2)
	/// Proof: `AgentAttestation::ModelProviders` (`max_values`: None, `max_size`: Some(323), added: 2798, mode: `MaxEncodedLen`)
	fn update_capability() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `6167`
		// Minimum execution time: 44_550_000 picoseconds.
		Weight::from_parts(51_441_000, 6167)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `AgentAttestation::Nodes` (r:1 w:0)
	/// Proof: `AgentAttestation::Nodes` (`max_values`: None, `max_size`: Some(223), added: 2698, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::MinerClaimCount` (r:1 w:1)
	/// Proof: `AgentAttestation::MinerClaimCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::MinerBenchmark` (r:1 w:1)
	/// Proof: `AgentAttestation::MinerBenchmark` (`max_values`: None, `max_size`: Some(330), added: 2805, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::NextBenchmarkClaimId` (r:1 w:1)
	/// Proof: `AgentAttestation::NextBenchmarkClaimId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:0 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	fn submit_benchmark_claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `3795`
		// Minimum execution time: 81_320_000 picoseconds.
		Weight::from_parts(90_120_000, 3795)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:1 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn challenge_benchmark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `416`
		//  Estimated: `3859`
		// Minimum execution time: 64_430_000 picoseconds.
		Weight::from_parts(73_880_000, 3859)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:1 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn resolve_benchmark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `3859`
		// Minimum execution time: 89_870_000 picoseconds.
		Weight::from_parts(96_281_000, 3859)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `AgentAttestation::MinerBenchmark` (r:1 w:0)
	/// Proof: `AgentAttestation::MinerBenchmark` (`max_values`: None, `max_size`: Some(330), added: 2805, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::BenchmarkClaims` (r:1 w:1)
	/// Proof: `AgentAttestation::BenchmarkClaims` (`max_values`: None, `max_size`: Some(394), added: 2869, mode: `MaxEncodedLen`)
	fn update_benchmark_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3859`
		// Minimum execution time: 42_540_000 picoseconds.
		Weight::from_parts(47_420_000, 3859)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
