
//! Autogenerated weights for `pallet_agent_attestation`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-22, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boxhire-cloud`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_agent_attestation
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/agent-attestation/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_agent_attestation`.
pub trait WeightInfo {
	fn register_node() -> Weight;
	fn heartbeat() -> Weight;
	fn submit_attestation() -> Weight;
	fn challenge_attestation() -> Weight;
	fn confirm_attestation() -> Weight;
	fn resolve_challenge() -> Weight;
	fn update_capability() -> Weight;
	fn submit_benchmark_claim() -> Weight;
	fn challenge_benchmark() -> Weight;
	fn resolve_benchmark() -> Weight;
	fn update_benchmark_score() -> Weight;
}

/// Weight functions for .
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: AgentAttestation Nodes (r:1 w:1)
	/// Proof: AgentAttestation Nodes (max_values: None, max_size: Some(223), added: 2698, mode: MaxEncodedLen)
	fn register_node() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3688`
		// Minimum execution time: 16_215_000 picoseconds.
		Weight::from_parts(18_782_000, 0)
			.saturating_add(Weight::from_parts(0, 3688))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: AgentAttestation Nodes (r:1 w:1)
	/// Proof: AgentAttestation Nodes (max_values: None, max_size: Some(223), added: 2698, mode: MaxEncodedLen)
	fn heartbeat() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `172`
		//  Estimated: `3688`
		// Minimum execution time: 19_257_000 picoseconds.
		Weight::from_parts(22_166_000, 0)
			.saturating_add(Weight::from_parts(0, 3688))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: AgentAttestation Nodes (r:1 w:0)
	/// Proof: AgentAttestation Nodes (max_values: None, max_size: Some(223), added: 2698, mode: MaxEncodedLen)
	/// Storage: AgentAttestation AttesterTaskCount (r:1 w:1)
	/// Proof: AgentAttestation AttesterTaskCount (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
	/// Storage: AgentAttestation NextAttestationId (r:1 w:1)
	/// Proof: AgentAttestation NextAttestationId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: AgentAttestation Attestations (r:0 w:1)
	/// Proof: AgentAttestation Attestations (max_values: None, max_size: Some(436), added: 2911, mode: MaxEncodedLen)
	fn submit_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `3688`
		// Minimum execution time: 46_112_000 picoseconds.
		Weight::from_parts(52_570_000, 0)
			.saturating_add(Weight::from_parts(0, 3688))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: AgentAttestation Attestations (r:1 w:1)
	/// Proof: AgentAttestation Attestations (max_values: None, max_size: Some(436), added: 2911, mode: MaxEncodedLen)
	fn challenge_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3901`
		// Minimum execution time: 21_132_000 picoseconds.
		Weight::from_parts(23_690_000, 0)
			.saturating_add(Weight::from_parts(0, 3901))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: AgentAttestation Attestations (r:1 w:1)
	/// Proof: AgentAttestation Attestations (max_values: None, max_size: Some(436), added: 2911, mode: MaxEncodedLen)
	/// Storage: X402Settlement NextIntentId (r:1 w:1)
	/// Proof: X402Settlement NextIntentId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: X402Settlement SettlementReceipts (r:0 w:1)
	/// Proof: X402Settlement SettlementReceipts (max_values: None, max_size: Some(152), added: 2627, mode: MaxEncodedLen)
	fn confirm_attestation() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3901`
		// Minimum execution time: 54_402_000 picoseconds.
		Weight::from_parts(61_206_000, 0)
			.saturating_add(Weight::from_parts(0, 3901))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: AgentAttestation Attestations (r:1 w:1)
	/// Proof: AgentAttestation Attestations (max_values: None, max_size: Some(436), added: 2911, mode: MaxEncodedLen)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `352`
		//  Estimated: `3901`
		// Minimum execution time: 54_125_000 picoseconds.
		Weight::from_parts(56_298_000, 0)
			.saturating_add(Weight::from_parts(0, 3901))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: AgentAttestation Nodes (r:1 w:0)
	/// Proof: AgentAttestation Nodes (max_values: None, max_size: Some(223), added: 2698, mode: MaxEncodedLen)
	/// Storage: AgentAttestation AgentCapabilities (r:1 w:1)
	/// Proof: AgentAttestation AgentCapabilities (max_values: None, max_size: Some(2702), added: 5177, mode: MaxEncodedLen)
	/// Storage: AgentAttestation ModelProviders (r:0 w:2)
	/// Proof: AgentAttestation ModelProviders (max_values: None, max_size: Some(323), added: 2798, mode: MaxEncodedLen)
	fn update_capability() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `6167`
		// Minimum execution time: 26_241_000 picoseconds.
		Weight::from_parts(28_862_000, 0)
			.saturating_add(Weight::from_parts(0, 6167))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: AgentAttestation Nodes (r:1 w:0)
	/// Proof: AgentAttestation Nodes (max_values: None, max_size: Some(223), added: 2698, mode: MaxEncodedLen)
	/// Storage: AgentAttestation MinerClaimCount (r:1 w:1)
	/// Proof: AgentAttestation MinerClaimCount (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: AgentAttestation MinerBenchmark (r:1 w:1)
	/// Proof: AgentAttestation MinerBenchmark (max_values: None, max_size: Some(330), added: 2805, mode: MaxEncodedLen)
	/// Storage: AgentAttestation NextBenchmarkClaimId (r:1 w:1)
	/// Proof: AgentAttestation NextBenchmarkClaimId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: AgentAttestation BenchmarkClaims (r:0 w:1)
	/// Proof: AgentAttestation BenchmarkClaims (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	fn submit_benchmark_claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `147`
		//  Estimated: `3795`
		// Minimum execution time: 49_736_000 picoseconds.
		Weight::from_parts(52_416_000, 0)
			.saturating_add(Weight::from_parts(0, 3795))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: AgentAttestation BenchmarkClaims (r:1 w:1)
	/// Proof: AgentAttestation BenchmarkClaims (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn challenge_benchmark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `416`
		//  Estimated: `3859`
		// Minimum execution time: 41_447_000 picoseconds.
		Weight::from_parts(42_211_000, 0)
			.saturating_add(Weight::from_parts(0, 3859))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: AgentAttestation BenchmarkClaims (r:1 w:1)
	/// Proof: AgentAttestation BenchmarkClaims (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn resolve_benchmark() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `468`
		//  Estimated: `3859`
		// Minimum execution time: 55_887_000 picoseconds.
		Weight::from_parts(57_680_000, 0)
			.saturating_add(Weight::from_parts(0, 3859))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: AgentAttestation MinerBenchmark (r:1 w:0)
	/// Proof: AgentAttestation MinerBenchmark (max_values: None, max_size: Some(330), added: 2805, mode: MaxEncodedLen)
	/// Storage: AgentAttestation BenchmarkClaims (r:1 w:1)
	/// Proof: AgentAttestation BenchmarkClaims (max_values: None, max_size: Some(394), added: 2869, mode: MaxEncodedLen)
	fn update_benchmark_score() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `347`
		//  Estimated: `3859`
		// Minimum execution time: 24_134_000 picoseconds.
		Weight::from_parts(27_527_000, 0)
			.saturating_add(Weight::from_parts(0, 3859))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	fn register_node() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn heartbeat() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn submit_attestation() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn challenge_attestation() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn confirm_attestation() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn resolve_challenge() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn update_capability() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn submit_benchmark_claim() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn challenge_benchmark() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn resolve_benchmark() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn update_benchmark_score() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}
