
//! Autogenerated weights for `pallet_zk_compute`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `dbc-benchmark`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /root/dbc3/target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_zk_compute
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// /root/dbc3/pallets/zk-compute/src/weights.rs
// --template
// /root/dbc3/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_zk_compute`.
pub trait WeightInfo {
	fn submit_proof() -> Weight;
	fn verify_task() -> Weight;
	fn claim_reward() -> Weight;
	fn submit_verification_unsigned() -> Weight;
}

/// Weights for `pallet_zk_compute` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ZkCompute::UsedNonces` (r:1 w:1)
	/// Proof: `ZkCompute::UsedNonces` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerScores` (r:1 w:0)
	/// Proof: `ZkCompute::MinerScores` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerPendingCount` (r:1 w:1)
	/// Proof: `ZkCompute::MinerPendingCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::NextTaskId` (r:1 w:1)
	/// Proof: `ZkCompute::NextTaskId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::PendingTasks` (r:1 w:1)
	/// Proof: `ZkCompute::PendingTasks` (`max_values`: Some(1), `max_size`: Some(8002), added: 8497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::Tasks` (r:0 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `9487`
		// Minimum execution time: 131_042_000 picoseconds.
		Weight::from_parts(155_923_000, 9487)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ZkCompute::Tasks` (r:1 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::PendingTasks` (r:1 w:1)
	/// Proof: `ZkCompute::PendingTasks` (`max_values`: Some(1), `max_size`: Some(8002), added: 8497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerPendingCount` (r:1 w:1)
	/// Proof: `ZkCompute::MinerPendingCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerScores` (r:1 w:1)
	/// Proof: `ZkCompute::MinerScores` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn verify_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `603`
		//  Estimated: `9487`
		// Minimum execution time: 262_653_000 picoseconds.
		Weight::from_parts(292_665_000, 9487)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ZkCompute::Tasks` (r:1 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `530`
		//  Estimated: `7681`
		// Minimum execution time: 232_029_000 picoseconds.
		Weight::from_parts(331_538_000, 7681)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ZkCompute::Tasks` (r:1 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::PendingTasks` (r:1 w:1)
	/// Proof: `ZkCompute::PendingTasks` (`max_values`: Some(1), `max_size`: Some(8002), added: 8497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerPendingCount` (r:1 w:1)
	/// Proof: `ZkCompute::MinerPendingCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::VerifiedTasks` (r:1 w:1)
	/// Proof: `ZkCompute::VerifiedTasks` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerScores` (r:1 w:1)
	/// Proof: `ZkCompute::MinerScores` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn submit_verification_unsigned() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `81487`
		// Minimum execution time: 168_399_000 picoseconds.
		Weight::from_parts(182_353_000, 81487)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ZkCompute::UsedNonces` (r:1 w:1)
	/// Proof: `ZkCompute::UsedNonces` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerScores` (r:1 w:0)
	/// Proof: `ZkCompute::MinerScores` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerPendingCount` (r:1 w:1)
	/// Proof: `ZkCompute::MinerPendingCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::NextTaskId` (r:1 w:1)
	/// Proof: `ZkCompute::NextTaskId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::PendingTasks` (r:1 w:1)
	/// Proof: `ZkCompute::PendingTasks` (`max_values`: Some(1), `max_size`: Some(8002), added: 8497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::Tasks` (r:0 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `9487`
		// Minimum execution time: 131_042_000 picoseconds.
		Weight::from_parts(155_923_000, 9487)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ZkCompute::Tasks` (r:1 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::PendingTasks` (r:1 w:1)
	/// Proof: `ZkCompute::PendingTasks` (`max_values`: Some(1), `max_size`: Some(8002), added: 8497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerPendingCount` (r:1 w:1)
	/// Proof: `ZkCompute::MinerPendingCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerScores` (r:1 w:1)
	/// Proof: `ZkCompute::MinerScores` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn verify_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `603`
		//  Estimated: `9487`
		// Minimum execution time: 262_653_000 picoseconds.
		Weight::from_parts(292_665_000, 9487)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ZkCompute::Tasks` (r:1 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `530`
		//  Estimated: `7681`
		// Minimum execution time: 232_029_000 picoseconds.
		Weight::from_parts(331_538_000, 7681)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ZkCompute::Tasks` (r:1 w:1)
	/// Proof: `ZkCompute::Tasks` (`max_values`: None, `max_size`: Some(4216), added: 6691, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::PendingTasks` (r:1 w:1)
	/// Proof: `ZkCompute::PendingTasks` (`max_values`: Some(1), `max_size`: Some(8002), added: 8497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerPendingCount` (r:1 w:1)
	/// Proof: `ZkCompute::MinerPendingCount` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::VerifiedTasks` (r:1 w:1)
	/// Proof: `ZkCompute::VerifiedTasks` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	/// Storage: `ZkCompute::MinerScores` (r:1 w:1)
	/// Proof: `ZkCompute::MinerScores` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	fn submit_verification_unsigned() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `81487`
		// Minimum execution time: 168_399_000 picoseconds.
		Weight::from_parts(182_353_000, 81487)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
