
//! Autogenerated weights for `pallet_zk_compute`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-22, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boxhire-cloud`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_zk_compute
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/zk-compute/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_zk_compute`.
pub trait WeightInfo {
	fn submit_proof() -> Weight;
	fn verify_task() -> Weight;
	fn claim_reward() -> Weight;
	fn submit_verification_unsigned() -> Weight;
}

/// Weight functions for .
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ZkCompute UsedNonces (r:1 w:1)
	/// Proof: ZkCompute UsedNonces (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
	/// Storage: ZkCompute MinerScores (r:1 w:0)
	/// Proof: ZkCompute MinerScores (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: ZkCompute MinerPendingCount (r:1 w:1)
	/// Proof: ZkCompute MinerPendingCount (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: ZkCompute NextTaskId (r:1 w:1)
	/// Proof: ZkCompute NextTaskId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: ZkCompute PendingTasks (r:1 w:1)
	/// Proof: ZkCompute PendingTasks (max_values: Some(1), max_size: Some(8002), added: 8497, mode: MaxEncodedLen)
	/// Storage: ZkCompute Tasks (r:0 w:1)
	/// Proof: ZkCompute Tasks (max_values: None, max_size: Some(4216), added: 6691, mode: MaxEncodedLen)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `180`
		//  Estimated: `9487`
		// Minimum execution time: 55_518_000 picoseconds.
		Weight::from_parts(59_213_000, 0)
			.saturating_add(Weight::from_parts(0, 9487))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: ZkCompute Tasks (r:1 w:1)
	/// Proof: ZkCompute Tasks (max_values: None, max_size: Some(4216), added: 6691, mode: MaxEncodedLen)
	/// Storage: ZkCompute PendingTasks (r:1 w:1)
	/// Proof: ZkCompute PendingTasks (max_values: Some(1), max_size: Some(8002), added: 8497, mode: MaxEncodedLen)
	/// Storage: ZkCompute MinerPendingCount (r:1 w:1)
	/// Proof: ZkCompute MinerPendingCount (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: ZkCompute MinerScores (r:1 w:1)
	/// Proof: ZkCompute MinerScores (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn verify_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `603`
		//  Estimated: `9487`
		// Minimum execution time: 85_488_000 picoseconds.
		Weight::from_parts(98_972_000, 0)
			.saturating_add(Weight::from_parts(0, 9487))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: ZkCompute Tasks (r:1 w:1)
	/// Proof: ZkCompute Tasks (max_values: None, max_size: Some(4216), added: 6691, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `530`
		//  Estimated: `7681`
		// Minimum execution time: 87_103_000 picoseconds.
		Weight::from_parts(103_639_000, 0)
			.saturating_add(Weight::from_parts(0, 7681))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: ZkCompute Tasks (r:1 w:1)
	/// Proof: ZkCompute Tasks (max_values: None, max_size: Some(4216), added: 6691, mode: MaxEncodedLen)
	/// Storage: ZkCompute PendingTasks (r:1 w:1)
	/// Proof: ZkCompute PendingTasks (max_values: Some(1), max_size: Some(8002), added: 8497, mode: MaxEncodedLen)
	/// Storage: ZkCompute MinerPendingCount (r:1 w:1)
	/// Proof: ZkCompute MinerPendingCount (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: ZkCompute VerifiedTasks (r:1 w:1)
	/// Proof: ZkCompute VerifiedTasks (max_values: Some(1), max_size: Some(80002), added: 80497, mode: MaxEncodedLen)
	/// Storage: ZkCompute MinerScores (r:1 w:1)
	/// Proof: ZkCompute MinerScores (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	fn submit_verification_unsigned() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `502`
		//  Estimated: `81487`
		// Minimum execution time: 50_629_000 picoseconds.
		Weight::from_parts(56_879_000, 0)
			.saturating_add(Weight::from_parts(0, 81487))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
}

impl WeightInfo for () {
	fn submit_proof() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn verify_task() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn claim_reward() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn submit_verification_unsigned() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}
