
//! Autogenerated weights for `pallet_task_mode`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-22, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boxhire-cloud`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_task_mode
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/task-mode/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_task_mode`.
pub trait WeightInfo {
	fn create_task_definition() -> Weight;
	fn update_task_definition() -> Weight;
	fn create_task_order() -> Weight;
	fn mark_order_completed() -> Weight;
	fn settle_task_order() -> Weight;
	fn cancel_expired_order() -> Weight;
}

/// Weight functions for .
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: TaskMode NextTaskId (r:1 w:1)
	/// Proof: TaskMode NextTaskId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskDefinitions (r:0 w:1)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	fn create_task_definition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1493`
		// Minimum execution time: 15_754_000 picoseconds.
		Weight::from_parts(16_594_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TaskMode TaskDefinitions (r:1 w:1)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	fn update_task_definition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `5104`
		// Minimum execution time: 18_923_000 picoseconds.
		Weight::from_parts(19_767_000, 0)
			.saturating_add(Weight::from_parts(0, 5104))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TaskMode TaskDefinitions (r:1 w:0)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	/// Storage: DBCPriceOCW AvgPrice (r:1 w:0)
	/// Proof Skipped: DBCPriceOCW AvgPrice (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: TaskMode NextOrderId (r:1 w:1)
	/// Proof: TaskMode NextOrderId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskOrders (r:0 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	fn create_task_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `329`
		//  Estimated: `5104`
		// Minimum execution time: 49_907_000 picoseconds.
		Weight::from_parts(50_340_000, 0)
			.saturating_add(Weight::from_parts(0, 5104))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	fn mark_order_completed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3687`
		// Minimum execution time: 18_619_000 picoseconds.
		Weight::from_parts(19_425_000, 0)
			.saturating_add(Weight::from_parts(0, 3687))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskDefinitions (r:1 w:0)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TaskMode EraStats (r:1 w:1)
	/// Proof: TaskMode EraStats (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: TaskMode MinerTaskStats (r:1 w:1)
	/// Proof: TaskMode MinerTaskStats (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	fn settle_task_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `567`
		//  Estimated: `5104`
		// Minimum execution time: 89_451_000 picoseconds.
		Weight::from_parts(92_967_000, 0)
			.saturating_add(Weight::from_parts(0, 5104))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	fn cancel_expired_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3687`
		// Minimum execution time: 37_225_000 picoseconds.
		Weight::from_parts(37_877_000, 0)
			.saturating_add(Weight::from_parts(0, 3687))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	fn create_task_definition() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn update_task_definition() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn create_task_order() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn mark_order_completed() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn settle_task_order() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn cancel_expired_order() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}
