
//! Autogenerated weights for `pallet_task_mode`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-20, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boxhire-cloud`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_task_mode
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/task-mode/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_task_mode`.
pub trait WeightInfo {
	fn create_task_definition() -> Weight;
	fn update_task_definition() -> Weight;
	fn create_task_order() -> Weight;
	fn mark_order_completed() -> Weight;
	fn settle_task_order() -> Weight;
	fn cancel_expired_order() -> Weight;
}

/// Weights for `pallet_task_mode` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: TaskMode NextTaskId (r:1 w:1)
	/// Proof: TaskMode NextTaskId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskDefinitions (r:0 w:1)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	fn create_task_definition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1493`
		// Minimum execution time: 15_396_000 picoseconds.
		Weight::from_parts(17_427_000, 1493)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: TaskMode TaskDefinitions (r:1 w:1)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	fn update_task_definition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `5104`
		// Minimum execution time: 18_626_000 picoseconds.
		Weight::from_parts(19_054_000, 5104)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TaskMode TaskDefinitions (r:1 w:0)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	/// Storage: DBCPriceOCW AvgPrice (r:1 w:0)
	/// Proof Skipped: DBCPriceOCW AvgPrice (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: TaskMode NextOrderId (r:1 w:1)
	/// Proof: TaskMode NextOrderId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskOrders (r:0 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	fn create_task_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `329`
		//  Estimated: `5104`
		// Minimum execution time: 50_083_000 picoseconds.
		Weight::from_parts(51_233_000, 5104)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	fn mark_order_completed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3687`
		// Minimum execution time: 18_580_000 picoseconds.
		Weight::from_parts(21_283_000, 3687)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskDefinitions (r:1 w:0)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TaskMode EraStats (r:1 w:1)
	/// Proof: TaskMode EraStats (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: TaskMode MinerTaskStats (r:1 w:1)
	/// Proof: TaskMode MinerTaskStats (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	fn settle_task_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `567`
		//  Estimated: `5104`
		// Minimum execution time: 89_316_000 picoseconds.
		Weight::from_parts(91_481_000, 5104)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn cancel_expired_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3687`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 3687)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: TaskMode NextTaskId (r:1 w:1)
	/// Proof: TaskMode NextTaskId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskDefinitions (r:0 w:1)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	fn create_task_definition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `4`
		//  Estimated: `1493`
		// Minimum execution time: 15_396_000 picoseconds.
		Weight::from_parts(17_427_000, 1493)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: TaskMode TaskDefinitions (r:1 w:1)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	fn update_task_definition() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `188`
		//  Estimated: `5104`
		// Minimum execution time: 18_626_000 picoseconds.
		Weight::from_parts(19_054_000, 5104)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TaskMode TaskDefinitions (r:1 w:0)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	/// Storage: DBCPriceOCW AvgPrice (r:1 w:0)
	/// Proof Skipped: DBCPriceOCW AvgPrice (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: TaskMode NextOrderId (r:1 w:1)
	/// Proof: TaskMode NextOrderId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskOrders (r:0 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	fn create_task_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `329`
		//  Estimated: `5104`
		// Minimum execution time: 50_083_000 picoseconds.
		Weight::from_parts(51_233_000, 5104)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	fn mark_order_completed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3687`
		// Minimum execution time: 18_580_000 picoseconds.
		Weight::from_parts(21_283_000, 3687)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	/// Storage: TaskMode TaskDefinitions (r:1 w:0)
	/// Proof: TaskMode TaskDefinitions (max_values: None, max_size: Some(1639), added: 4114, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: TaskMode EraStats (r:1 w:1)
	/// Proof: TaskMode EraStats (max_values: None, max_size: Some(68), added: 2543, mode: MaxEncodedLen)
	/// Storage: TaskMode MinerTaskStats (r:1 w:1)
	/// Proof: TaskMode MinerTaskStats (max_values: None, max_size: Some(84), added: 2559, mode: MaxEncodedLen)
	fn settle_task_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `567`
		//  Estimated: `5104`
		// Minimum execution time: 89_316_000 picoseconds.
		Weight::from_parts(91_481_000, 5104)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: TaskMode TaskOrders (r:1 w:1)
	/// Proof: TaskMode TaskOrders (max_values: None, max_size: Some(222), added: 2697, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn cancel_expired_order() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `283`
		//  Estimated: `3687`
		// Minimum execution time: 25_000_000 picoseconds.
		Weight::from_parts(26_000_000, 3687)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
