
//! Autogenerated weights for `pallet_x402_settlement`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-02, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ubuntu-2004`, CPU: `Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_x402_settlement
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/x402-settlement/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x402_settlement`.
pub trait WeightInfo {
	fn submit_payment_intent() -> Weight;
	fn verify_settlement() -> Weight;
	fn finalize_settlement() -> Weight;
	fn fail_payment_intent() -> Weight;
}

/// Weights for `pallet_x402_settlement` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `X402Settlement::NonceUsed` (r:1 w:1)
	/// Proof: `X402Settlement::NonceUsed` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::ReplayFingerprintUsed` (r:1 w:1)
	/// Proof: `X402Settlement::ReplayFingerprintUsed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::NextIntentId` (r:1 w:1)
	/// Proof: `X402Settlement::NextIntentId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PendingIntentIds` (r:1 w:1)
	/// Proof: `X402Settlement::PendingIntentIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PaymentIntents` (r:0 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	fn submit_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `81487`
		// Minimum execution time: 81_370_000 picoseconds.
		Weight::from_parts(88_200_000, 81487)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `X402Settlement::PaymentIntents` (r:1 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PendingIntentIds` (r:1 w:1)
	/// Proof: `X402Settlement::PendingIntentIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	fn verify_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `81487`
		// Minimum execution time: 41_190_000 picoseconds.
		Weight::from_parts(48_760_000, 81487)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `X402Settlement::PaymentIntents` (r:1 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::SettlementReceipts` (r:0 w:1)
	/// Proof: `X402Settlement::SettlementReceipts` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn finalize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `506`
		//  Estimated: `3766`
		// Minimum execution time: 88_441_000 picoseconds.
		Weight::from_parts(96_880_000, 3766)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `X402Settlement::PaymentIntents` (r:1 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PendingIntentIds` (r:1 w:1)
	/// Proof: `X402Settlement::PendingIntentIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	fn fail_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `81487`
		// Minimum execution time: 69_820_000 picoseconds.
		Weight::from_parts(75_130_000, 81487)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `X402Settlement::NonceUsed` (r:1 w:1)
	/// Proof: `X402Settlement::NonceUsed` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::ReplayFingerprintUsed` (r:1 w:1)
	/// Proof: `X402Settlement::ReplayFingerprintUsed` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::NextIntentId` (r:1 w:1)
	/// Proof: `X402Settlement::NextIntentId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PendingIntentIds` (r:1 w:1)
	/// Proof: `X402Settlement::PendingIntentIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PaymentIntents` (r:0 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	fn submit_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `81487`
		// Minimum execution time: 81_370_000 picoseconds.
		Weight::from_parts(88_200_000, 81487)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `X402Settlement::PaymentIntents` (r:1 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PendingIntentIds` (r:1 w:1)
	/// Proof: `X402Settlement::PendingIntentIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	fn verify_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `81487`
		// Minimum execution time: 41_190_000 picoseconds.
		Weight::from_parts(48_760_000, 81487)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `X402Settlement::PaymentIntents` (r:1 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::SettlementReceipts` (r:0 w:1)
	/// Proof: `X402Settlement::SettlementReceipts` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
	fn finalize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `506`
		//  Estimated: `3766`
		// Minimum execution time: 88_441_000 picoseconds.
		Weight::from_parts(96_880_000, 3766)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `X402Settlement::PaymentIntents` (r:1 w:1)
	/// Proof: `X402Settlement::PaymentIntents` (`max_values`: None, `max_size`: Some(301), added: 2776, mode: `MaxEncodedLen`)
	/// Storage: `X402Settlement::PendingIntentIds` (r:1 w:1)
	/// Proof: `X402Settlement::PendingIntentIds` (`max_values`: Some(1), `max_size`: Some(80002), added: 80497, mode: `MaxEncodedLen`)
	fn fail_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `399`
		//  Estimated: `81487`
		// Minimum execution time: 69_820_000 picoseconds.
		Weight::from_parts(75_130_000, 81487)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
