
//! Autogenerated weights for `pallet_x402_settlement`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-20, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boxhire-cloud`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_x402_settlement
// --extrinsic
// submit_payment_intent,verify_settlement,fail_payment_intent
// --steps
// 20
// --repeat
// 10
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/x402-settlement/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_x402_settlement`.
pub trait WeightInfo {
	fn submit_payment_intent() -> Weight;
	fn verify_settlement() -> Weight;
	fn fail_payment_intent() -> Weight;
	fn finalize_settlement() -> Weight;
}

/// Weights for `pallet_x402_settlement` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: X402Settlement NonceUsed (r:1 w:1)
	/// Proof: X402Settlement NonceUsed (max_values: None, max_size: Some(57), added: 2532, mode: MaxEncodedLen)
	/// Storage: X402Settlement ReplayFingerprintUsed (r:1 w:1)
	/// Proof: X402Settlement ReplayFingerprintUsed (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
	/// Storage: X402Settlement NextIntentId (r:1 w:1)
	/// Proof: X402Settlement NextIntentId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: X402Settlement PaymentIntents (r:0 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	fn submit_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `3522`
		// Minimum execution time: 44_645_000 picoseconds.
		Weight::from_parts(45_589_000, 3522)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: X402Settlement PaymentIntents (r:1 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	fn verify_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3762`
		// Minimum execution time: 21_957_000 picoseconds.
		Weight::from_parts(22_326_000, 3762)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: X402Settlement PaymentIntents (r:1 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	fn fail_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3762`
		// Minimum execution time: 37_841_000 picoseconds.
		Weight::from_parts(38_352_000, 3762)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: X402Settlement PaymentIntents (r:1 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	/// Storage: X402Settlement SettlementReceipts (r:0 w:1)
	/// Proof: X402Settlement SettlementReceipts (max_values: None, max_size: Some(137), added: 2612, mode: MaxEncodedLen)
	fn finalize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377` (estimated)
		//  Estimated: `3762`
		// Minimum execution time: 55_000_000 picoseconds (estimated from verify_settlement + balance transfer).
		Weight::from_parts(55_000_000, 3762)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}

}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: X402Settlement NonceUsed (r:1 w:1)
	/// Proof: X402Settlement NonceUsed (max_values: None, max_size: Some(57), added: 2532, mode: MaxEncodedLen)
	/// Storage: X402Settlement ReplayFingerprintUsed (r:1 w:1)
	/// Proof: X402Settlement ReplayFingerprintUsed (max_values: None, max_size: Some(49), added: 2524, mode: MaxEncodedLen)
	/// Storage: X402Settlement NextIntentId (r:1 w:1)
	/// Proof: X402Settlement NextIntentId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: X402Settlement PaymentIntents (r:0 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	fn submit_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `114`
		//  Estimated: `3522`
		// Minimum execution time: 44_645_000 picoseconds.
		Weight::from_parts(45_589_000, 3522)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: X402Settlement PaymentIntents (r:1 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	fn verify_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3762`
		// Minimum execution time: 21_957_000 picoseconds.
		Weight::from_parts(22_326_000, 3762)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: X402Settlement PaymentIntents (r:1 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	fn fail_payment_intent() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377`
		//  Estimated: `3762`
		// Minimum execution time: 37_841_000 picoseconds.
		Weight::from_parts(38_352_000, 3762)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: X402Settlement PaymentIntents (r:1 w:1)
	/// Proof: X402Settlement PaymentIntents (max_values: None, max_size: Some(297), added: 2772, mode: MaxEncodedLen)
	/// Storage: X402Settlement SettlementReceipts (r:0 w:1)
	/// Proof: X402Settlement SettlementReceipts (max_values: None, max_size: Some(137), added: 2612, mode: MaxEncodedLen)
	fn finalize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `377` (estimated)
		//  Estimated: `3762`
		// Minimum execution time: 55_000_000 picoseconds (estimated from verify_settlement + balance transfer).
		Weight::from_parts(55_000_000, 3762)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}

}
