
//! Autogenerated weights for `pallet_compute_pool_scheduler`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-20, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boxhire-cloud`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_compute_pool_scheduler
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --template
// .maintain/frame-weight-template.hbs
// --output
// pallets/compute-pool-scheduler/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_compute_pool_scheduler`.
pub trait WeightInfo {
	fn register_pool() -> Weight;
	fn update_pool_config() -> Weight;
	fn deregister_pool() -> Weight;
	fn submit_task() -> Weight;
	fn submit_proof() -> Weight;
	fn claim_reward() -> Weight;
	fn dispute_verification() -> Weight;
	fn on_initialize() -> Weight;
	fn stake_to_pool() -> Weight;
	fn unstake_from_pool() -> Weight;
}

/// Weights for `pallet_compute_pool_scheduler` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ComputePoolScheduler PoolByOwner (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolByOwner (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler NextPoolId (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler NextPoolId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	fn register_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3593`
		// Minimum execution time: 43_178_000 picoseconds.
		Weight::from_parts(44_970_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	fn update_pool_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 19_778_000 picoseconds.
		Weight::from_parts(20_245_000, 3782)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolByOwner (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolByOwner (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolTasks (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	fn deregister_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3899`
		// Minimum execution time: 49_695_000 picoseconds.
		Weight::from_parts(50_324_000, 3899)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: ComputePoolScheduler NextTaskId (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler NextTaskId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:2 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolTasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Tasks (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	fn submit_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `6447`
		// Minimum execution time: 96_944_000 picoseconds.
		Weight::from_parts(99_682_000, 6447)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolTasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	/// Storage: AgentAttestation NextAttestationId (r:1 w:1)
	/// Proof: AgentAttestation NextAttestationId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: AgentAttestation AttesterTaskCount (r:1 w:1)
	/// Proof: AgentAttestation AttesterTaskCount (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler Rewards (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	/// Storage: AgentAttestation Attestations (r:0 w:1)
	/// Proof: AgentAttestation Attestations (max_values: None, max_size: Some(436), added: 2911, mode: MaxEncodedLen)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `724`
		//  Estimated: `4189`
		// Minimum execution time: 115_938_000 picoseconds.
		Weight::from_parts(121_851_000, 4189)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(10_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Rewards (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `993`
		//  Estimated: `6196`
		// Minimum execution time: 86_721_000 picoseconds.
		Weight::from_parts(89_067_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler Rewards (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	fn dispute_verification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `985`
		//  Estimated: `6196`
		// Minimum execution time: 99_379_000 picoseconds.
		Weight::from_parts(100_783_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3666`
		// Minimum execution time: 6_164_000 picoseconds.
		Weight::from_parts(6_444_000, 3666)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolStakes (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolStakes (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TotalPoolStake (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TotalPoolStake (max_values: None, max_size: None, mode: Measured)
	fn stake_to_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `3855`
		// Minimum execution time: 45_216_000 picoseconds.
		Weight::from_parts(46_116_000, 3855)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: ComputePoolScheduler PoolStakes (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolStakes (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler TotalPoolStake (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TotalPoolStake (max_values: None, max_size: None, mode: Measured)
	fn unstake_from_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `3958`
		// Minimum execution time: 46_237_000 picoseconds.
		Weight::from_parts(47_004_000, 3958)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: ComputePoolScheduler PoolByOwner (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolByOwner (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler NextPoolId (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler NextPoolId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	fn register_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3593`
		// Minimum execution time: 43_178_000 picoseconds.
		Weight::from_parts(44_970_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	fn update_pool_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 19_778_000 picoseconds.
		Weight::from_parts(20_245_000, 3782)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolByOwner (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolByOwner (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolTasks (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	fn deregister_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3899`
		// Minimum execution time: 49_695_000 picoseconds.
		Weight::from_parts(50_324_000, 3899)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: ComputePoolScheduler NextTaskId (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler NextTaskId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:2 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolTasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Tasks (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	fn submit_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `6447`
		// Minimum execution time: 96_944_000 picoseconds.
		Weight::from_parts(99_682_000, 6447)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolTasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	/// Storage: AgentAttestation NextAttestationId (r:1 w:1)
	/// Proof: AgentAttestation NextAttestationId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: AgentAttestation AttesterTaskCount (r:1 w:1)
	/// Proof: AgentAttestation AttesterTaskCount (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler Rewards (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	/// Storage: AgentAttestation Attestations (r:0 w:1)
	/// Proof: AgentAttestation Attestations (max_values: None, max_size: Some(436), added: 2911, mode: MaxEncodedLen)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `724`
		//  Estimated: `4189`
		// Minimum execution time: 115_938_000 picoseconds.
		Weight::from_parts(121_851_000, 4189)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(10_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Rewards (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `993`
		//  Estimated: `6196`
		// Minimum execution time: 86_721_000 picoseconds.
		Weight::from_parts(89_067_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler Rewards (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	fn dispute_verification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `985`
		//  Estimated: `6196`
		// Minimum execution time: 99_379_000 picoseconds.
		Weight::from_parts(100_783_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `201`
		//  Estimated: `3666`
		// Minimum execution time: 6_164_000 picoseconds.
		Weight::from_parts(6_444_000, 3666)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolStakes (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolStakes (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TotalPoolStake (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TotalPoolStake (max_values: None, max_size: None, mode: Measured)
	fn stake_to_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `3855`
		// Minimum execution time: 45_216_000 picoseconds.
		Weight::from_parts(46_116_000, 3855)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: ComputePoolScheduler PoolStakes (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolStakes (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler TotalPoolStake (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TotalPoolStake (max_values: None, max_size: None, mode: Measured)
	fn unstake_from_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `3958`
		// Minimum execution time: 46_237_000 picoseconds.
		Weight::from_parts(47_004_000, 3958)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
}
