
//! Autogenerated weights for `pallet_compute_pool_scheduler`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-22, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `boxhire-cloud`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_compute_pool_scheduler
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --output
// pallets/compute-pool-scheduler/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_compute_pool_scheduler`.
pub trait WeightInfo {
	fn register_pool() -> Weight;
	fn update_pool_config() -> Weight;
	fn deregister_pool() -> Weight;
	fn submit_task() -> Weight;
	fn submit_proof() -> Weight;
	fn verify_proof() -> Weight;
	fn claim_reward() -> Weight;
	fn dispute_verification() -> Weight;
	fn on_initialize() -> Weight;
	fn stake_to_pool() -> Weight;
	fn unstake_from_pool() -> Weight;
	fn file_complaint() -> Weight;
	fn resolve_complaint() -> Weight;
	fn cancel_complaint() -> Weight;
	fn appeal_complaint() -> Weight;
}

/// Weight functions for .
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: ComputePoolScheduler PoolByOwner (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolByOwner (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler NextPoolId (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler NextPoolId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	fn register_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3593`
		// Minimum execution time: 42_959_000 picoseconds.
		Weight::from_parts(43_905_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	fn update_pool_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 19_885_000 picoseconds.
		Weight::from_parts(20_237_000, 0)
			.saturating_add(Weight::from_parts(0, 3782))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolByOwner (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolByOwner (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolTasks (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	fn deregister_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3899`
		// Minimum execution time: 49_437_000 picoseconds.
		Weight::from_parts(50_341_000, 0)
			.saturating_add(Weight::from_parts(0, 3899))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: ComputePoolScheduler NextTaskId (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler NextTaskId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:2 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolTasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Tasks (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	fn submit_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `6447`
		// Minimum execution time: 97_272_000 picoseconds.
		Weight::from_parts(98_876_000, 0)
			.saturating_add(Weight::from_parts(0, 6447))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ProofSubmittedAt (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler ProofSubmittedAt (max_values: None, max_size: None, mode: Measured)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `511`
		//  Estimated: `3976`
		// Minimum execution time: 34_487_000 picoseconds.
		Weight::from_parts(35_354_000, 0)
			.saturating_add(Weight::from_parts(0, 3976))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ActiveTaskCount (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler ActiveTaskCount (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolTasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	/// Storage: AgentAttestation NextAttestationId (r:1 w:1)
	/// Proof: AgentAttestation NextAttestationId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: AgentAttestation AttesterTaskCount (r:1 w:1)
	/// Proof: AgentAttestation AttesterTaskCount (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler Rewards (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler ProofSubmittedAt (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler ProofSubmittedAt (max_values: None, max_size: None, mode: Measured)
	/// Storage: AgentAttestation Attestations (r:0 w:1)
	/// Proof: AgentAttestation Attestations (max_values: None, max_size: Some(436), added: 2911, mode: MaxEncodedLen)
	fn verify_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `790`
		//  Estimated: `4255`
		// Minimum execution time: 108_705_000 picoseconds.
		Weight::from_parts(110_203_000, 0)
			.saturating_add(Weight::from_parts(0, 4255))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(11))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Rewards (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `994`
		//  Estimated: `6196`
		// Minimum execution time: 86_174_000 picoseconds.
		Weight::from_parts(88_456_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler MinerReputation (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler MinerReputation (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskEscrowStore (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskEscrowStore (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:2 w:2)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler Rewards (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Rewards (max_values: None, max_size: None, mode: Measured)
	fn dispute_verification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `986`
		//  Estimated: `6196`
		// Minimum execution time: 99_979_000 picoseconds.
		Weight::from_parts(101_158_000, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: ComputePoolScheduler PoolTasks (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler PoolTasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PendingComplaintSlash (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler PendingComplaintSlash (max_values: None, max_size: None, mode: Measured)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `164`
		//  Estimated: `3629`
		// Minimum execution time: 11_482_000 picoseconds.
		Weight::from_parts(11_804_000, 0)
			.saturating_add(Weight::from_parts(0, 3629))
			.saturating_add(T::DbWeight::get().reads(2))
	}
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolStakes (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolStakes (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TotalPoolStake (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TotalPoolStake (max_values: None, max_size: None, mode: Measured)
	fn stake_to_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `3855`
		// Minimum execution time: 45_106_000 picoseconds.
		Weight::from_parts(45_779_000, 0)
			.saturating_add(Weight::from_parts(0, 3855))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: ComputePoolScheduler PoolStakes (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolStakes (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler TotalPoolStake (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TotalPoolStake (max_values: None, max_size: None, mode: Measured)
	fn unstake_from_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `3958`
		// Minimum execution time: 46_196_000 picoseconds.
		Weight::from_parts(47_129_000, 0)
			.saturating_add(Weight::from_parts(0, 3958))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: ComputePoolScheduler Tasks (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Tasks (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler TaskComplaint (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler TaskComplaint (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolOpenComplaints (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolOpenComplaints (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler NextComplaintId (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler NextComplaintId (max_values: Some(1), max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Complaints (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler Complaints (max_values: None, max_size: None, mode: Measured)
	fn file_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `549`
		//  Estimated: `4014`
		// Minimum execution time: 50_982_000 picoseconds.
		Weight::from_parts(51_657_000, 0)
			.saturating_add(Weight::from_parts(0, 4014))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: ComputePoolScheduler Complaints (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Complaints (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler Pools (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PoolOpenComplaints (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolOpenComplaints (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PendingComplaintSlash (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PendingComplaintSlash (max_values: None, max_size: None, mode: Measured)
	fn resolve_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `826`
		//  Estimated: `4291`
		// Minimum execution time: 59_836_000 picoseconds.
		Weight::from_parts(60_890_000, 0)
			.saturating_add(Weight::from_parts(0, 4291))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(5))
	}
	/// Storage: ComputePoolScheduler Complaints (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Complaints (max_values: None, max_size: None, mode: Measured)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: ComputePoolScheduler PoolOpenComplaints (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler PoolOpenComplaints (max_values: None, max_size: None, mode: Measured)
	fn cancel_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 60_661_000 picoseconds.
		Weight::from_parts(61_630_000, 0)
			.saturating_add(Weight::from_parts(0, 4122))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: ComputePoolScheduler Complaints (r:1 w:1)
	/// Proof Skipped: ComputePoolScheduler Complaints (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler Pools (r:1 w:0)
	/// Proof Skipped: ComputePoolScheduler Pools (max_values: None, max_size: None, mode: Measured)
	/// Storage: ComputePoolScheduler PendingComplaintSlash (r:0 w:1)
	/// Proof Skipped: ComputePoolScheduler PendingComplaintSlash (max_values: None, max_size: None, mode: Measured)
	fn appeal_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4138`
		// Minimum execution time: 30_557_000 picoseconds.
		Weight::from_parts(31_250_000, 0)
			.saturating_add(Weight::from_parts(0, 4138))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}

impl WeightInfo for () {
	fn register_pool() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn update_pool_config() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn deregister_pool() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn submit_task() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn submit_proof() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn verify_proof() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn claim_reward() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn dispute_verification() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn on_initialize() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn stake_to_pool() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn unstake_from_pool() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn file_complaint() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn resolve_complaint() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn cancel_complaint() -> Weight {
		Weight::from_parts(10_000, 0)
	}
	fn appeal_complaint() -> Weight {
		Weight::from_parts(10_000, 0)
	}
}
