
//! Autogenerated weights for `pallet_compute_pool_scheduler`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `dbc-benchmark`, CPU: `Intel Xeon Processor (Skylake, IBRS)`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// /root/dbc3/target/release/dbc-chain
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_compute_pool_scheduler
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// /root/dbc3/pallets/compute-pool-scheduler/src/weights.rs
// --template
// /root/dbc3/.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_compute_pool_scheduler`.
pub trait WeightInfo {
	fn register_pool() -> Weight;
	fn update_pool_config() -> Weight;
	fn deregister_pool() -> Weight;
	fn submit_task() -> Weight;
	fn submit_proof() -> Weight;
	fn verify_proof() -> Weight;
	fn claim_reward() -> Weight;
	fn dispute_verification() -> Weight;
	fn on_initialize() -> Weight;
	fn stake_to_pool() -> Weight;
	fn unstake_from_pool() -> Weight;
	fn file_complaint() -> Weight;
	fn resolve_complaint() -> Weight;
	fn cancel_complaint() -> Weight;
	fn appeal_complaint() -> Weight;
}

/// Weights for `pallet_compute_pool_scheduler` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ComputePoolScheduler::PoolByOwner` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolByOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::NextPoolId` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::NextPoolId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::MinerReputation` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::MinerReputation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3593`
		// Minimum execution time: 106_326_000 picoseconds.
		Weight::from_parts(143_728_000, 3593)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_pool_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 45_937_000 picoseconds.
		Weight::from_parts(60_007_000, 3782)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolByOwner` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PoolByOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deregister_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3899`
		// Minimum execution time: 112_559_000 picoseconds.
		Weight::from_parts(184_271_000, 3899)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ComputePoolScheduler::NextTaskId` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::NextTaskId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:2 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskEscrowStore` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::TaskEscrowStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Tasks` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `6447`
		// Minimum execution time: 245_699_000 picoseconds.
		Weight::from_parts(353_865_000, 6447)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ProofSubmittedAt` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::ProofSubmittedAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `511`
		//  Estimated: `3976`
		// Minimum execution time: 79_349_000 picoseconds.
		Weight::from_parts(94_552_000, 3976)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::MinerReputation` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::MinerReputation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AgentAttestation::NextAttestationId` (r:1 w:1)
	/// Proof: `AgentAttestation::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::AttesterTaskCount` (r:1 w:1)
	/// Proof: `AgentAttestation::AttesterTaskCount` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::Rewards` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ProofSubmittedAt` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::ProofSubmittedAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AgentAttestation::Attestations` (r:0 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn verify_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `790`
		//  Estimated: `4255`
		// Minimum execution time: 264_719_000 picoseconds.
		Weight::from_parts(329_378_000, 4255)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(11_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Rewards` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskEscrowStore` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TaskEscrowStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `994`
		//  Estimated: `6196`
		// Minimum execution time: 220_126_000 picoseconds.
		Weight::from_parts(323_794_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::MinerReputation` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::MinerReputation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskEscrowStore` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TaskEscrowStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::Rewards` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn dispute_verification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `986`
		//  Estimated: `6196`
		// Minimum execution time: 296_472_000 picoseconds.
		Weight::from_parts(368_594_000, 6196)
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(7_u64))
	}
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PendingComplaintSlash` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::PendingComplaintSlash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `164`
		//  Estimated: `3629`
		// Minimum execution time: 22_878_000 picoseconds.
		Weight::from_parts(25_971_000, 3629)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolStakes` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolStakes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TotalPoolStake` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TotalPoolStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn stake_to_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `3855`
		// Minimum execution time: 97_336_000 picoseconds.
		Weight::from_parts(134_479_000, 3855)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ComputePoolScheduler::PoolStakes` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolStakes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::TotalPoolStake` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TotalPoolStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unstake_from_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `3958`
		// Minimum execution time: 106_026_000 picoseconds.
		Weight::from_parts(127_426_000, 3958)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskComplaint` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TaskComplaint` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolOpenComplaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolOpenComplaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::NextComplaintId` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::NextComplaintId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Complaints` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn file_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `549`
		//  Estimated: `4014`
		// Minimum execution time: 119_831_000 picoseconds.
		Weight::from_parts(168_849_000, 4014)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ComputePoolScheduler::Complaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolOpenComplaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolOpenComplaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PendingComplaintSlash` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PendingComplaintSlash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resolve_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `826`
		//  Estimated: `4291`
		// Minimum execution time: 120_628_000 picoseconds.
		Weight::from_parts(158_493_000, 4291)
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: `ComputePoolScheduler::Complaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolOpenComplaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolOpenComplaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 150_060_000 picoseconds.
		Weight::from_parts(203_527_000, 4122)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
	}
	/// Storage: `ComputePoolScheduler::Complaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PendingComplaintSlash` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PendingComplaintSlash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn appeal_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4138`
		// Minimum execution time: 74_654_000 picoseconds.
		Weight::from_parts(83_019_000, 4138)
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `ComputePoolScheduler::PoolByOwner` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolByOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::NextPoolId` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::NextPoolId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::MinerReputation` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::MinerReputation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn register_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `107`
		//  Estimated: `3593`
		// Minimum execution time: 106_326_000 picoseconds.
		Weight::from_parts(143_728_000, 3593)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn update_pool_config() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `317`
		//  Estimated: `3782`
		// Minimum execution time: 45_937_000 picoseconds.
		Weight::from_parts(60_007_000, 3782)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolByOwner` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PoolByOwner` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn deregister_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `434`
		//  Estimated: `3899`
		// Minimum execution time: 112_559_000 picoseconds.
		Weight::from_parts(184_271_000, 3899)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ComputePoolScheduler::NextTaskId` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::NextTaskId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:2 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskEscrowStore` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::TaskEscrowStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Tasks` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_task() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `507`
		//  Estimated: `6447`
		// Minimum execution time: 245_699_000 picoseconds.
		Weight::from_parts(353_865_000, 6447)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ProofSubmittedAt` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::ProofSubmittedAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn submit_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `511`
		//  Estimated: `3976`
		// Minimum execution time: 79_349_000 picoseconds.
		Weight::from_parts(94_552_000, 3976)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ActiveTaskCount` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::ActiveTaskCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::MinerReputation` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::MinerReputation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AgentAttestation::NextAttestationId` (r:1 w:1)
	/// Proof: `AgentAttestation::NextAttestationId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `AgentAttestation::AttesterTaskCount` (r:1 w:1)
	/// Proof: `AgentAttestation::AttesterTaskCount` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::Rewards` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::ProofSubmittedAt` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::ProofSubmittedAt` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AgentAttestation::Attestations` (r:0 w:1)
	/// Proof: `AgentAttestation::Attestations` (`max_values`: None, `max_size`: Some(436), added: 2911, mode: `MaxEncodedLen`)
	fn verify_proof() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `790`
		//  Estimated: `4255`
		// Minimum execution time: 264_719_000 picoseconds.
		Weight::from_parts(329_378_000, 4255)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(11_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Rewards` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskEscrowStore` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TaskEscrowStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn claim_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `994`
		//  Estimated: `6196`
		// Minimum execution time: 220_126_000 picoseconds.
		Weight::from_parts(323_794_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::MinerReputation` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::MinerReputation` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskEscrowStore` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TaskEscrowStore` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::Rewards` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Rewards` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn dispute_verification() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `986`
		//  Estimated: `6196`
		// Minimum execution time: 296_472_000 picoseconds.
		Weight::from_parts(368_594_000, 6196)
			.saturating_add(RocksDbWeight::get().reads(6_u64))
			.saturating_add(RocksDbWeight::get().writes(7_u64))
	}
	/// Storage: `ComputePoolScheduler::PoolTasks` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::PoolTasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PendingComplaintSlash` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::PendingComplaintSlash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn on_initialize() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `164`
		//  Estimated: `3629`
		// Minimum execution time: 22_878_000 picoseconds.
		Weight::from_parts(25_971_000, 3629)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
	}
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolStakes` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolStakes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TotalPoolStake` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TotalPoolStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn stake_to_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `3855`
		// Minimum execution time: 97_336_000 picoseconds.
		Weight::from_parts(134_479_000, 3855)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ComputePoolScheduler::PoolStakes` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolStakes` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::TotalPoolStake` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TotalPoolStake` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn unstake_from_pool() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `493`
		//  Estimated: `3958`
		// Minimum execution time: 106_026_000 picoseconds.
		Weight::from_parts(127_426_000, 3958)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ComputePoolScheduler::Tasks` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Tasks` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::TaskComplaint` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::TaskComplaint` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolOpenComplaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolOpenComplaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::NextComplaintId` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::NextComplaintId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Complaints` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn file_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `549`
		//  Estimated: `4014`
		// Minimum execution time: 119_831_000 picoseconds.
		Weight::from_parts(168_849_000, 4014)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ComputePoolScheduler::Complaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PoolOpenComplaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolOpenComplaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PendingComplaintSlash` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PendingComplaintSlash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn resolve_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `826`
		//  Estimated: `4291`
		// Minimum execution time: 120_628_000 picoseconds.
		Weight::from_parts(158_493_000, 4291)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: `ComputePoolScheduler::Complaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ComputePoolScheduler::PoolOpenComplaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::PoolOpenComplaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn cancel_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `657`
		//  Estimated: `4122`
		// Minimum execution time: 150_060_000 picoseconds.
		Weight::from_parts(203_527_000, 4122)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	/// Storage: `ComputePoolScheduler::Complaints` (r:1 w:1)
	/// Proof: `ComputePoolScheduler::Complaints` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::Pools` (r:1 w:0)
	/// Proof: `ComputePoolScheduler::Pools` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ComputePoolScheduler::PendingComplaintSlash` (r:0 w:1)
	/// Proof: `ComputePoolScheduler::PendingComplaintSlash` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn appeal_complaint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `673`
		//  Estimated: `4138`
		// Minimum execution time: 74_654_000 picoseconds.
		Weight::from_parts(83_019_000, 4138)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
}
